### ISSUE TITLE
How to handle leaf encoding with array of struct ?

### ISSUE THREAD

**Issue by quentinmassias** [OpenZeppelin/merkle-tree#12]
Hello, I need for my project to use a merkle tree with each leaf containing an array of Solidity struct, here is the TypeScript equivalent interface of my struct :
```typescript
interface Order {
  adapter: string; // an address type in Solidity
  signature: string; // e.g. : "swap(address,address,address,uint256)"
  parameters: BytesLike; // parameters of the above signature encoded with ethers.js abiCoder.encode() function
}
```

For the moment, I directly pass for each leaf an array of Order like this :
```typescript
StandardMerkleTree.of([strategy1Orders, strategy2Orders], ["Order[]"]);
```

Obviously, the `leafEncoding` does not work with `Order[]` value and I get that error :

> types/values length mismatch (count={"types":1,"values":3}, value={"types":["Order[]"],"values":[{"adapter":"0xc8A22654d7C0b301DFe57e2D93F8E04C0c859388","signature":"swap(address,address,address,uint256)","parameters":"0x0000000000000000000000007ceb23fd6bc0add59e62ac25578270cff1b9f6190000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa84174"},{"adapter":"0x10Df2A2Be7FCa0A22587C0876eAaE4275535f8b8","signature":"borrow(address,uint8,address,uint256)","parameters":"0x0000000000000000000000003fd939b017b31eaadf9ae50c7ff7fa5c0661d47c0000000000000000000000000000000000000000000000000000000000000032"},{"adapter":"0xF8727f2d6b46e7003f20A2F97422E33Da42d76c7","signature":"deposit(address,address,address,uint256)","parameters":"0x000000000000000000000000ebe0c8d842aa5a57d7bef8e524deaba676f91cd1000000000000000000000000a3fa99a148fa48d14ed51d610c367c61876997f1"}]}

Even if it is not directly related with my error, here is my Solidity code for the verify part :
```solidity
bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(orders))));
require(MerkleProof.verifyCalldata(proof, root, leaf) == true, "invalid merkle proof");
```
note: `orders` being a `Order[] calldata` with this Order struct :
```solidity
struct Order {
    address adapter;
    string signature;
    bytes parameters;
}
```

I was thinking of maybe encoding the `strategy1Orders` with keccak256 for example to have not an array of Order anymore but bytes and I would have to do the same keccak256 encoding around `leaf` variable in Solidity, but that is just an idea, maybe there is a better way to handle struct and especially array of struct in my case with Merkle Tree.

Thanks a lot in advance for your help, and do not hesitate to ask more details if needed !

**Comment by Amxx** [comment]
The library internally uses ethers.js for the encodeing. The relevant documentation is [here](https://docs.ethers.org/v5/api/utils/abi/coder/#AbiCoder-encode). 

In your case you should probably be doing something like

```StandardMerkleTree.of([strategy1Orders, strategy2Orders], ["tuple(address,string,bytes)[]"]);``

**Comment by quentinmassias** [comment]
Thanks for the quick answer, indeed, that documentation helped me and as you mentioned, it was just a misunderstanding of the AbiCoder !

It was a bit tricky tho, to make the `leafEncoding` works with `["tuple(address adapter, string signature, bytes parameters)[]"]`, I had to encapsulate each `strategy*Orders` inside an array, otherwise the `leafEncoding` expected was an array with X times the value `"tuple(address adapter, string signature, bytes parameters)"` where X is the number of Order in my `strategy*Orders`. Cause this X is dynamic depending of the `strategy*Orders`, I could not afford that and finished up with that :

```typescript
StandardMerkleTree.of([[strategy1Orders], [strategy2Orders]], ["tuple(address adapter, string signature, bytes parameters)[]"]);
```

**Comment by frangio** [comment]
I've added the link to AbiCoder docs in the readme.

https://github.com/OpenZeppelin/merkle-tree#standardmerkletreeof
