### ISSUE TITLE
I hope the compiled code is compatible with the lower execution environment. I have encountered the syntax problem of es2020

### ISSUE THREAD

**Issue by lirong098** [OpenZeppelin/merkle-tree#14]
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     }
|     leafLookup(leaf) {
>         return this.hashLookup[this.leafHash(leaf)] ?? (0, throw_error_1.throwError)('Leaf is not in tree');
|     }
|     getProof(leaf) {

**Comment by lirong098** [comment]
?? Change to | | Normal execution

**Comment by frangio** [comment]
You need to use at least Node 14.

**Comment by lirong098** [comment]
> 您至少需要使用 Node 14。



> You need to use at least Node 14.

I use Node 14.19.3. However, in the webpage project, Babel must be configured to support es2020 before it can run normally. In my opinion, for open source libraries, we should consider es2015. thank you.

**Comment by frangio** [comment]
Sorry, it's better for users if we ship ES2020 code. If a user needs to target an older version they will need to use a transpiler.
