### ISSUE TITLE
Update contract Verifier - "Validating a Proof in Solidity"

### ISSUE THREAD

**Issue by santiagotrujilloz** [OpenZeppelin/merkle-tree#17]
In the [README](https://github.com/OpenZeppelin/merkle-tree#readme) in the section "Validating a Proof in Solidity" line (2) is not compiling anymore:
`bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(addr, amount))));`

instead of this, I tried the following and it verified successfully:
`bytes32 leaf = keccak256(abi.encodePacked(keccak256(abi.encode(addr, amount))));`

```
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

contract Verifier {
    bytes32 private root;

    constructor(bytes32 _root) {
        // (1)
        root = _root;
    }

    function verify(
        bytes32[] memory proof,
        address addr,
        uint256 amount
    ) public {
        // (2)
        bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(addr, amount))));
        // (3)
        require(MerkleProof.verify(proof, root, leaf), "Invalid proof");
        // (4)
        // ...
    }
}
```

**Comment by Amxx** [comment]
Which version of the compiler are you using ?

```solidity
bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(addr, amount))));
```
is valid since 0.8.4

**Comment by santiagotrujilloz** [comment]
Ohh right, I was using 0.8.0, thanks!
