### ISSUE TITLE
The argument of type 'Buffer' cannot be assigned to the parameter of type 'string'.

### ISSUE THREAD

**Issue by vseae** [OpenZeppelin/merkle-tree#25]
**bug**
  ```
  const tree = StandardMerkleTree.load(
    JSON.parse(fs.readFileSync("scripts/tree.json"))
  );
  console.log(tree.root);
```
  **fix:**
```
fs.readFileSync("scripts/tree.json").toString()
```

**Comment by Amxx** [comment]
Hello @vseae

Can you be more explicit about the situation that leads to an issue ? Is that issue just about the example in the readme, or did you find that bug in the source code of the library?

**Comment by frangio** [comment]
This is a TypeScript type error, even though the code works at runtime. You have to add the encoding as a second argument.

Fixed in https://github.com/OpenZeppelin/merkle-tree/commit/0951d3ca036d44c61e33fd9731750cf0ce2978c3.
