### ISSUE TITLE
How to get the double-hashed value in solidity?

### ISSUE THREAD

**Issue by TiheChen** [OpenZeppelin/merkle-tree#4]
I use this lib to generate multi proof for MerkleProof.sol use and it works fine!
However, I found out that the hashLeaf function is to double hash the value, so I try to do it in solidity like this
```solidity
keccak256(abi.encodePacked(keccak256(abi.encodePacked("Test")))));
```
but the result is not the same as that from hashLeaf function on @openzeppelin/merkle-tree lib.
If I want to generate double hash value in solidity, how do i do?

```
keccak256(abi.encodePacked(keccak256(abi.encodePacked("Test"))))) : 0x2380b87d3868c7b4fc9c6fbdf21c5410bbfc6486bf5b478c89e77880c5dd5919
tree.hashLeaf(["Test"]) : 0x45584dfe70323c546d4297daadcceb9c657174eb3f24c2f8857cbaaf861bf1ba
```

**Comment by TiheChen** [comment]
Sorry, I found the solution on README
```solidity
keccak256(bytes.concat(keccak256(abi.encode("Test"))))
```

**Comment by frangio** [comment]
Glad you found it. I added `leafHash` which was missing from the API docs and included the Solidity snippet in there as well.
