### ISSUE TITLE
No Verify method

### ISSUE THREAD

**Issue by duktig666** [OpenZeppelin/merkle-tree#8]
Hope that JS can implement the Verify method of Merkle

**Comment by Amxx** [comment]
Hello @duktig666 

`core.ts` includes 2 functions
- [`processProof`](https://github.com/OpenZeppelin/merkle-tree/blob/master/src/core.ts#L56)
- [`processMultiProof`](https://github.com/OpenZeppelin/merkle-tree/blob/master/src/core.ts#L107)
that you can use to process rebuild the tree root given a leaf (or leaves) and a proof (or multiproof)

The result of these can then be compared to the correct root to verify the correctness.

```tree.proof == processProof(tree.hashLeaf(leaf), tree.getProof(leaf))```

**Comment by frangio** [comment]
> `tree.root == processProof(tree.hashLeaf(leaf), tree.getProof(leaf))`

It's not so simple because StandardMerkleTree represents hashes as strings, and the core module represents hashes and leaves as Uint8Array.

I've created #10 to add the functions in StandardMerkleTree.

**Comment by duktig666** [comment]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/MerkleProof.sol

I think it would be more intuitive and easy to use if js code provided a verify method like solidity's.

```
function verify(bytes32[] memory proof, bytes32 root, bytes32 leaf) internal pure returns (bool) {
    return processProof(proof, leaf) == root;
}
```

Conversely, if solidity can provide `StandardMerkleTree.of` in js code, you can generate merkle methods. That would be even better.

**Comment by duktig666** [comment]
https://github.com/OpenZeppelin/merkle-tree/pull/10

Can Tree call verify directly?

**Comment by frangio** [comment]
@duktig666 What do you mean?

**Comment by duktig666** [comment]
Is there a method like `tree.verify` that can be called?

Or how to use it now to verify leaf nodes

**Comment by frangio** [comment]
Yes see the readme: https://github.com/OpenZeppelin/merkle-tree#treeverify

`tree` should be an instance of `StandardMerkleTree`.

**Comment by duktig666** [comment]
OK, this should be just added. Thank you

**Comment by slavik0329** [comment]
[https://github.com/OpenZeppelin/merkle-tree/pull/15](See this pull request #15)
