### ISSUE TITLE
Cannot get successful proofs in contract

### ISSUE THREAD

**Issue by bitbeckers** [OpenZeppelin/merkle-tree#9]
For a project we want to allowlist users to mint a 1155 token with a predefined value based on their address We are able to succesfully store a merkle tree and retrieve proofs, but the contract rejects them when submitting the proofs..

The submitted transaction reverts with`Invalid()`. We've matched the spec in the Readme as closely as possibly, beside some changes specific to our usecase. Is there something missing in the way we either submit the data or parse the tree?

This is kinda blocking for us, but since `merkletreejs` underlines the need to use your package with your contracts we hope you can help us resolve this 🙏 

### Allowlist
Values will be address and fraction/units as a string.
```javascript
const initialValues = {
  contributors: [
    {
      address: "",
      fraction: "",
    },
    {
      address: "",
      fraction: "",
    },
    {
      address: "",
      fraction: "",
    },
  ],
};
```

### Store
This step build the allowlist and stores the merkleroot for a token in the contract
```javascript
    // Entries to arrays
    const mappedEntries = validEntries.map((validEntry) => [
      validEntry.address,
      validEntry.fraction,
    ]);

    const tree = StandardMerkleTree.of(mappedEntries, ["address", "uint256"]);
    const cid = await storeData(JSON.stringify(tree.dump()), client);
```

### Retrieve
```javascript
      const treeResponse = await getData(merkleCID);

      if (!treeResponse) {
        return;
      }

      setMerkleTree(StandardMerkleTree.load(JSON.parse(treeResponse)));
```

### Get Proof
The amount of allowlisted unit is correct, so we are certain the retrieval of the proofs works.
```javascript
    const findProof = (tree: StandardMerkleTree<(string | number)[]>) => {
      for (const [i, v] of tree.entries()) {
        if (v[0] === address) {
          const proof = tree.getProof(i);
          setMerkleProofs(proof);
          setUnits(Number(v[1]));
        }
      }
    };
```

### WAGMI transaction builder
```javascript
. . .
   args: [
      args.proof as `0x{string}`[],
      BigNumber.from(args.claimID),
      BigNumber.from(args.units),
    ],
    abi: HyperCertMinterFactory.abi,
    functionName: "mintClaimFromAllowlist",
. . .
```

### Solidity method in AllowlisMinter contract
```solidity
    function _processClaim(bytes32[] calldata proof, uint256 claimID, uint256 amount) internal {
        console.log("CALL _processAllowlist: ");
        // console.log(proof);
        for (uint256 i = 0; i < proof.length; i++) {
            console.logBytes32(proof[i]);
        }
        console.log(claimID);
        console.log(amount);

        if (merkleRoots[claimID].length == 0) revert DoesNotExist();

        bytes32 node = keccak256(bytes.concat(keccak256(abi.encodePacked(msg.sender, amount))));

        if (hasBeenClaimed[claimID][node]) revert DuplicateEntry();
        if (!MerkleProofUpgradeable.verifyCalldata(proof, merkleRoots[claimID], node)) revert Invalid();
        hasBeenClaimed[claimID][node] = true;

        emit LeafClaimed(claimID, node);
    }
```

**Comment by Amxx** [comment]
Hello @bitbeckers 

There is quite a lot of information to process here. Can you confirm that 
- `tree.root` matches `merkleRoots[claimID]` ?
- `tree.leafHash(address, amount)` matches the `bytes32 node` ?

**Comment by bitbeckers** [comment]
Hi @Amxx , thanks for the quick response and apologies for the codedump. We did some additional inspection and logging for your questions and found:

tree.root matches merkleRoots[claimID] => Yes
tree.leafHash(address, amount) matches the bytes32 node => No

We see that the correct root is stored for the correct tokenID, but the leaf value calculated does not match. 

For example:
Front end:
```bash
Tree:  0) f1ef5e66fa78313ec3d3617a44c21a9061f1c87437f512625a50a5a29335a647
├─ 1) 9fbeead82035b70a90ee6513e2db4ad0d36783e079ca198c9c2cef0ab8aa3871
│  ├─ 3) c5e527d3335339cf4e1a1efa6daa1737709616c24c3592816fc90628ba4c6988
│  └─ 4) adaabd42cd37b5c2e6dc112232db5bfa51cd00e448bd923d793e986971d1b5a2
└─ 2) cdfe40dfe738e7133fbafefb3b5d825e18baa84151378dfd29e15d69221d8d32
```

Contract
```bash
    ClaimID:  340282366920938463463374607431768211456
    MerkleRoot: 
    0xf1ef5e66fa78313ec3d3617a44c21a9061f1c87437f512625a50a5a29335a647
    Leaf: 
    0x68393c3615dc9dc5957ef2c9e532f82c6127048a3c144c411b2a1a36b3e2ccf5
 ```

 Using tree.leafHash we got:
`Leaf:  0xc5e527d3335339cf4e1a1efa6daa1737709616c24c3592816fc90628ba4c6988`

 To dig deeper, we tried different data patters permutating over encoding types [`uint256`, `uint`, `string`]   and data types [`string`, `number`] but nothing returned the expected leaf value as provided by the contract.

**Comment by Amxx** [comment]
I think I found your issue.

```diff
-        bytes32 node = keccak256(bytes.concat(keccak256(abi.encodePacked(msg.sender, amount))));
+        bytes32 node = keccak256(bytes.concat(keccak256(abi.encode(msg.sender, amount))));
```

Can you try that and let me know?

**Comment by bitbeckers** [comment]
It worked! So stupid we missed this one. Thanks a million for you support!
